version: "3"
  services:
    service1:
      build:
        context: ./bin/serivce_one
      container_name: 'service_one'
      restart: 'always'
      depends_on:
        - mysql
      networks:
        - backend
      volumes:
        - ./www:/var/www/html
   service2:
      build:
        context: ./bin/service_two
      container_name: 'service_two'
      restart: 'always'
      depends_on:
        - mysql
      networks:
        - backend
      volumes:
        - ./www:/var/www/html

  nginx:
    image: .
    container_name: 'nginx'
    restart: 'always'
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mysql:
    image: percona
    container_name: '5.8-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./data/_db:/home/databases
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./config/mysql:/docker-entrypoint-initdb.d

    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root_P@ssw0rd
networks:
  backend:
